# Generated by Django 3.2.8 on 2021-10-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glyph', models.CharField(max_length=255)),
                ('dungeon_type', models.CharField(max_length=255)),
                ('fetid', models.BooleanField()),
                ('rotten', models.BooleanField()),
                ('cursed', models.BooleanField()),
                ('shape', models.CharField(max_length=255)),
                ('gem_type', models.CharField(max_length=255)),
                ('first_effect', models.CharField(max_length=255)),
                ('second_effect', models.CharField(max_length=255)),
                ('third_effect', models.CharField(max_length=255)),
                ('rarity', models.IntegerField()),
                ('layer', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
